[package]
name = "my-bitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bitcoin = { version = "0.32.2", features = ["rand-std"] }
hex = "0.4.3"
